name = "ai-court-hr-portal"
main = "src/index.js"
compatibility_date = "2026-09-12"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
AMBIGUOUS_API_URL = "https://app.ambiguous.ai/api"
CANDIDATE_SHEET_TITLE = "Candidate Pool"
CHOSEN_SHEET_TITLE = "chosen"
